---
title: External doc update from ${{ env.PR_NUMBER }}
labels: documentation
---

Update the external documentation:

- Author: '@${{ payload.sender.login }}'
- PR: ${{ env.PR_URL }}
- Modified files: ${{ env.CHANGED_FILES }}
