name: Suggest a new page or section
description: Suggest new content for the documentation
title: "Doc: "
labels: ["documentation"]
assignees:
  - cnivolle
  - juliamrch
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new content form!
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Checking for existing issue
      description: Have you checked your request hasn't been already addressed in another issue?
      options:
        - label: I have checked for existing [issues](https://github.com/CleverCloud/documentation/issues)
          required: true
  - type: textarea
    id: describe-content
    attributes:
      label: "Describe the content you'd like to see"
      description: "A clear and concise description of what you want to happen."
      placeholder: "I'd like to have a new page/section about…"
    validations:
      required: true
