name: Track external documentation updates

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]

jobs:
  external-documentation:
    runs-on: ubuntu-latest
    name: Check externally maintained guides
    environment: update doc
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Find guides mirrored in external documentation
        id: changed-files-specific
        uses: tj-actions/changed-files@v47
        with:
          files: |
            content/guides/astro.md
            content/guides/nuxt.md
      
      - name: Create or update tracking issue
        id: create-issue
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.number }}
          CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/external-doc-issue.yml
          assignees: ${{ github.event.pull_request.user.login }}
          update_existing: true
          search_existing: all
