name: Check editorial style
on: [pull_request]

jobs:
  vale:
    name: Run Vale Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: vale-cli/vale-action@v3
        with:
          filter_mode: added
          fail_on_error: false
